// part of '../ui/pages/pages.dart';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:fms_app/model/api_service.dart';
import 'package:fms_app/model/msbudget.dart';
import 'package:fms_app/model/msbudget_.dart';
import 'package:fms_app/model/msemployee.dart';
import 'package:fms_app/model/msequipment.dart';
import 'package:fms_app/model/msrefueling.dart';
import 'package:fms_app/model/msshift.dart';
import 'package:fms_app/model/mssite.dart';
import 'package:fms_app/model/msstorage.dart';
import 'package:fms_app/model/tr_baps.dart';
import 'package:fms_app/model/tr_fuel_attendace.dart';
import 'package:fms_app/model/tr_fuel_distribution.dart';
import 'package:fms_app/model/tr_fuel_transfer.dart';
import 'package:fms_app/model/tr_refueling.dart';
import 'package:fms_app/model/tr_sounding.dart';
import 'package:fms_app/model/tr_sounding_.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sqflite/sqflite.dart';
import 'package:postgres/postgres.dart';
// import 'package:json_annotation/json_annotation.dart';

part 'db_local.dart';
part 'fms_database.dart';
