// pages ini berfungsi untuk menghubungkan semua halaman agar bisa dipanggil di setiap widget

// import 'dart:io' show Platform;
import 'dart:developer';
import 'dart:io' ;
import 'package:flutter/foundation.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:fms_app/bloc/blocs.dart';
import 'package:fms_app/model/msbudget.dart';
import 'package:fms_app/model/msbudget_.dart';
import 'package:fms_app/model/msemployee.dart';
import 'package:fms_app/model/msrefueling.dart';
import 'package:fms_app/model/msshift.dart';
import 'package:fms_app/model/mssite.dart';
import 'package:fms_app/model/msstorage.dart';
import 'package:fms_app/model/tr_sounding_.dart';
import 'package:path/path.dart' as filePath;
import 'dart:typed_data';
import 'dart:async';
import 'dart:convert';
import 'package:fms_app/bloc/blocs.dart';
import 'package:fms_app/database/db_package.dart';
import 'package:fms_app/model/tr_fuel_transfer.dart';
import 'package:fms_app/model/tr_baps.dart';
import 'package:fms_app/model/api_service.dart';
import 'package:fms_app/model/msequipment.dart';
import 'package:fms_app/model/tr_fuel_attendace.dart';
import 'package:fms_app/model/tr_sounding.dart';
import 'package:fms_app/model/tr_sounding_.dart';
import 'package:fms_app/model/tr_refueling.dart';
import 'package:fms_app/model/checkbox_value.dart';
import 'package:date_format/date_format.dart';
import 'package:path_provider/path_provider.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';
import 'package:flutter/services.dart';
import 'package:flutter/rendering.dart';
import 'package:fms_app/style/style.dart';
import 'package:file_picker/file_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;
import 'package:permission_handler/permission_handler.dart';
import 'package:signature/signature.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';
import 'package:camera/camera.dart';

part 'login/welcome.dart';
part 'login/login1.dart';
part 'home/homeDashboard.dart';
part 'home/homeTransaksi.dart';
part 'home/homeDetailTransaksi.dart';
part 'home/detail_history_transaksi.dart';
part 'home/homeBAPS.dart';
part 'home/homeTemplate.dart';
part 'home/homeLansiran.dart';
part 'home/homeSounding.dart';
part 'home/homeManual.dart';
part 'home/homeNotifikasi.dart';
part 'extend widget/comboboxDropdown.dart';
part 'extend widget/shiftDropdown.dart';
part 'extend widget/uploaderDropdown.dart';
part 'extend widget/signaturePad.dart';
part 'extend widget/camera.dart';
part 'extend widget/search.dart';
part 'home/home.dart';
part 'extend widget/settingsDropdown.dart';
part 'extend widget/loadingBar.dart';
part 'extend widget/display_camera.dart';
part 'scan/scanner.dart';
part 'scan/scanFailed.dart';
part 'scan/scanRefueling.dart';
part 'scan/SelectedScanner.dart';
part 'scan/operatorDropdown.dart';
part '../../global/variable.dart';
part 'profile/profile.dart';
part 'profile/changePassword.dart';
part 'profile/forgotPassword.dart';
part 'profile/verification.dart';
part 'wrapper.dart';
